### ISSUE TITLE
triggers are never released and remain in 'acquired' state

### ISSUE THREAD

**Issue by oxygensar** [FlavioF/quartz-scheduler-hazelcast-jobstore#1]
i think you need to set trigger state to 'waiting' in triggersFired() method i.e do:

 // call triggered on our copy, and the scheduler's copy
      tw.trigger.triggered(cal);
      trigger.triggered(cal);
      // tw.state = TriggerWrapper.STATE_EXECUTING;
      **storeTriggerWrapper(newTriggerWrapper(trigger, WAITING));**

**Comment by FlavioF** [comment]
Hi! Sorry for the delay answering.

Thanks for the contribution. I will take a look into it as soon as possible, but you are probably right.
