### ISSUE TITLE
Unstable build

### ISSUE THREAD

**Issue by anton-johansson** [FlavioF/quartz-scheduler-hazelcast-jobstore#18]
Hi!

It looks like the build is unstable. I've seen it sometimes when building locally, and also when Travis CI builds.

Any idea why? And are there plans to fix it?

**Comment by FlavioF** [comment]
Yes, it is probably a race condition in test suite. I will take a look into it asap.

**Comment by FlavioF** [comment]
Afaik there is only one or two tests that are failing. It looks that it is a problem in slow PCs. I tryied to run the suite test 100 times in my PC and it never failed. I need to try it in my laptop in order to solve the problem.
