### ISSUE TITLE
Non-graceful shutdown

### ISSUE THREAD

**Issue by anton-johansson** [FlavioF/quartz-scheduler-hazelcast-jobstore#20]
I'm having some problems with non-graceful shutdowns.

Scenario 1:
I have two nodes running Hazelcast and Quartz. It runs OK. I then **gracefully** shutdown the first node. The jobs will keep running on the second node. Everything works good!

Scenario 2:
I have two nodes running Hazelcast and Quartz. It runs OK. I then **non-gracefully** shutdown the first node. The jobs will stop running. Not good!

I believe this is because we use a queue and we're not protected against forced shutdowns. For example, if I have a single job, and node A gets into ```acquireNextTriggers``` and runs ```triggers.poll()```, the queue will be empty. Then directly afterwards, node A crashes. The trigger will never be put back on the queue.

Any ideas? Maybe we should look at the default JDBC JobStore to see how they implemented this?

**Comment by FlavioF** [comment]
Yes, you are probably right. Can you implement a test that replicate the second scenario?

Looking to JDBC JobStore could be a good idea. We should probably implement any type of transaction or lock. Maybe something like Hazelcast TransactionalQueue, idk. Take a look into it if you want (http://docs.hazelcast.org/docs/3.5/manual/html/transactions.html).

Do you think that you can handle this issue?

Thank you for your input.

**Comment by anton-johansson** [comment]
I'll take a look at it once I have some time over.

**Comment by anton-johansson** [comment]
I have one idea (that I haven't explored further yet):

 * Get rid of ```triggers``` (the ```IQueue``` field)
 * Get rid of ```TriggerState.ACQUIRED```
 * Use ```triggersByKey.values(...)``` and pass in a predicate to get triggers that should be fired
 * Loop them (only the keys that aren't locked)
 * Try to lock them, and if OK, return them as triggered
 * Do not unlock until we get into ```#triggersFired``` or ```#releaseAcquiredTrigger```
 * Crashed Hazelcast nodes will automatically release locks (AFAIK), which means they will automatically be put back in the "queue".

Can you see any obvious problems or issues with this idea?

I'd like to explore this idea further, but it's hard as long as the build is unstable. It's not easy for me to know if I've broken any other unit tests.

Anyway, I'll start working on a way to simulate my issue in a unit test.

**Comment by FlavioF** [comment]
Let me think about it. I need some time to think since in the past we already used triggersByKey.values(...) and we found a problem on it. I need to recall it.

Information about unstable build #18 

Yes a test to replicate your issue would be very nice.

Thank you for all the help.

**Comment by FlavioF** [comment]
Thank you for your patience on waiting. I cannot remove the queue since it is ensuring order (FIFO as possible as it can be in a distributed system). And it is important in some use cases. 

I am trying to found a solution for it. Is there already any test to replicate the failing scenario?

**Comment by anton-johansson** [comment]
No, I haven't had the time to work on a test to reproduce this issue. I will as soon as I can, unless someone else does it first.

Using a Hazelcast predicate would guarantee FIFO too, would it not? I'm not 100% familiar with predicates, but it feels like Hazelcast would manage that.

**Comment by FlavioF** [comment]
No, if you are using a map there is no way to guarantee FIFO afaik.

**Comment by anton-johansson** [comment]
You're right. But is FIFO really what you want?

Correct me if I'm wrong, but in the current state of the code, all triggers reside within the ```triggers``` queue unless they are currently being fired. What happens if a new trigger is created, whose ```nextFireTime``` is much earlier than the last trigger on the queue. It will still be put at the end of the queue. Correct? This means, one trigger that should be fired earlier than some others, will be fired after those triggers. Sure, it's FIFO, but is it really correct behavior?

To me, it feels using a predicate to fetch triggers from Hazelcast, then sorting them locally, is the best option. Do you have any thoughts? I'm just spawning ideas here. :)

I **think** I have managed to get a unit test working for this. Check out the latest commit in the ```ungraceful-shutdown```-branch in my fork:
https://github.com/anton-johansson/quartz-scheduler-hazelcast-jobstore/tree/ungraceful-shutdown

**Comment by FlavioF** [comment]
I implemented FIFO because it was needed as described in #5.

Maybe FIFO is not the correct behavior. Idk. Need to think. For now I will try to figure out how to avoid loose triggers with the queue.
Later we need to decide if FIFO is the correct behavior or not. By "we" I mean all the people involved including me ofc :)

Honestly, I am starting to think that FIFO is not a good idea, it is to much complex to be supported by a distributed JobStore. Lets see.. 

If it can't be done with the queue probably I will kill the FIFO feature.

Tyvm for the test
