### ISSUE TITLE
Job stop running for some random reason

### ISSUE THREAD

**Issue by FlavioF** [FlavioF/quartz-scheduler-hazelcast-jobstore#23]
"We are seeing an issue where our jobs stop running for some random reason. In one example we noticed that a job stopped running this past Saturday and the "nextfireTime" seems to be stuck at Sat Mar 19 2016 19:34:49”. It is not changing for this particular job. I'm not sure if this is a symptom or a cause of why the job isn't running. I would expect that if the nextfireTime is in the past, the scheduler should notice and run it as soon as it "wakes up". But I don't know the exact way it works internally.

Based on your experience working with quartz, do you have any idea what might be going on if a job suddenly stops running? Do you have an idea where we might want to debug to find more information?"
By Andreas Schmidt

**Comment by FlavioF** [comment]
Waiting for more information...

**Comment by rvanderwerf** [comment]
what if the quartz job crashed... do you have error handling with a
try/catch in your job to catch and log if it crashes?

**Comment by kuseman** [comment]
Seems like it can be the same issue as  https://github.com/FlavioF/quartz-scheduler-hazelcast-jobstore/issues/20

**Comment by FlavioF** [comment]
Duplicates #20
