### ISSUE TITLE
Assert-parameters incorrect order

### ISSUE THREAD

**Issue by anton-johansson** [FlavioF/quartz-scheduler-hazelcast-jobstore#27]
I've seen that many (all?) parameters to the Assert-methods are in the wrong order. For example:
```Assert.assertEquals(7, triggers.size());```

See method definition:
```org.testng.Assert.assertEquals(int actual, int expected)```

This differs from JUnit, where the expected value is usually first, maybe that's where it's been a mixup. Anyway, just thought put an issue for it, since it gives some weird and confusing outputs:
```java.lang.AssertionError: expected [0] but found [7]```

Btw, out of curiousity, is there any particular reason for using TestNG over JUnit? I've never worked with TestNG before.

**Comment by FlavioF** [comment]
Yes, I know. ;) I need to change it but not urgent for now.

I like the flavour of TestNG! And I like a lot the Before/After Suite/Test annotations and the group and method dependencies. But in this case the choice was only because I like the flavour of TestNG. :P

**Comment by anton-johansson** [comment]
Yeah, of course not urgent. :)

Allright!
