### ISSUE TITLE
A misfired trigger is acquired if the nextFireTime is within the range of current 'acquire window'

### ISSUE THREAD

**Issue by tri123** [FlavioF/quartz-scheduler-hazelcast-jobstore#33]
When acquiring next triggers to fire, the acquireNextTriggers detects misfired triggers and will update the trigger to the next fire time, making it eligible for the NEXT acquireNextTriggers call. This given issues with triggers that execute more regular than the acquireNextTriggers. They will always misfire and won't ever be picked up.

The solution is simple: if the next fire time of a misfired trigger lies within the interval of current acquire, pick it up in current acquireNextTriggers. (I have the patch availble and will commit it asap)

**Comment by FlavioF** [comment]
Ok, please create a test that replicates it firstly.

Thank you for your contribution.

**Comment by tri123** [comment]
Of course, can I create a branch for that so you can check it out there? I think I don't have the rights to do that (or I can't seem to find the button anyway).

**Comment by FlavioF** [comment]
Yes. Create a branch and create a pull request. :+1:

**Comment by tri123** [comment]
I'd love to, but pushig a new local branch to GitHub gives a 403 - or should I create it via GitHub UI? (I'm not really used to working with github and don't seem to find where to create new branches)

**Comment by FlavioF** [comment]
https://help.github.com/articles/creating-a-pull-request/
