### ISSUE TITLE
logback.xml should not be shipped within jar file

### ISSUE THREAD

**Issue by iesen** [FlavioF/quartz-scheduler-hazelcast-jobstore#38]
The jar package contains logback.xml files, which cause issues project using logback.
It give this warning at startup

> 10:31:31,447 |-WARN in ch.qos.logback.classic.LoggerContext Resource [logback.xml] occurs multiple times on the classpath.
10:31:31,447 |-WARN in ch.qos.logback.classic.LoggerContext Resource [logback.xml] occurs at [jar:file:/Users/homr/.m2/repository/com/bikeemotion/quartz-hazelcast-jobstore/1.0.1/quartz-hazelcast-jobstore-1.0.1.jar!/logback.xml]

**Comment by FlavioF** [comment]
Duplicates #24
