### ISSUE TITLE
scheduler.unscheduleJobs not always having any effect

### ISSUE THREAD

**Issue by anton-johansson** [FlavioF/quartz-scheduler-hazelcast-jobstore#43]
## Problem

When any of my jobs change (for example, trigger interval is changed, a parameter is changed, etc), I want to re-schedule it. I do this by first unscheduling any existing triggers for the job and then schedule it like I usually do.

But it seems that the unscheduling doesn't always actually unschedule. So when I re-schedule, it sometimes runs on multiple nodes (depending on the node it schedules on).
## Code

I've tried both of these:

``` java
List<TriggerKey> triggers = scheduler.getTriggersOfJob(detail.getKey())
        .stream()
        .map(Trigger::getKey)
        .collect(toList());
scheduler.unscheduleJobs(triggers);
scheduler.scheduleJob(detail, new HashSet<>(asList(trigger)), true);
```

``` java
scheduler.deleteJob(detail.getKey());
scheduler.scheduleJob(detail, trigger);
```

Both generate the same issue.
## How to reproduce

I've created a sample project where the issue can be reproduced. See [anton-johansson/quartz-hazelcast-jobstore-samples/#43](https://github.com/anton-johansson/quartz-hazelcast-jobstore-samples/tree/master/quartz-hazelcast-jobstore-samples-43).

**Comment by anton-johansson** [comment]
Anyone have a clue about this? Or maybe an idea where to start debugging and investigating?

**Comment by FlavioF** [comment]
I will take a look into it next week.

**Comment by anton-johansson** [comment]
Awesome, thanks a bunch! If you want, keep me updated with progress, maybe I can help. :)

**Comment by anton-johansson** [comment]
Any news on this? :)

**Comment by FlavioF** [comment]
It looks to be a concurrency problem when removing triggers.

**Comment by anton-johansson** [comment]
Even with the sample project I supplied?

**Comment by FlavioF** [comment]
Yes! I will try it again today. Are you using the last version of the job store?

**Comment by anton-johansson** [comment]
I just ran my sample again, and I cannot reproduce it... Very strange. I cannot see any commits since I tried last time. :S

**Comment by FlavioF** [comment]
Yes, it is probably a rare race condition.

**Comment by anton-johansson** [comment]
Yeah, the issue still exists in our environment, using the latest snapshot. I'll see if I can find a better way to reproduce it.

**Comment by FlavioF** [comment]
Hi! Any news on this? 👍

**Comment by anton-johansson** [comment]
Hey! Unfortunately not... =/ Having some trouble reproducing it in an isolated environment, together with lack of time.

**Comment by FlavioF** [comment]
Not reproducible. Will be open again if we can reproduce it.
